// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFc1ItFKevZuBt2tKM7r2NuqIceBpZ_4',
    appId: '1:413352872203:web:0af31382638d66c7053a0e',
    messagingSenderId: '413352872203',
    projectId: 'grasp-a122f',
    authDomain: 'grasp-a122f.firebaseapp.com',
    storageBucket: 'grasp-a122f.appspot.com',
    measurementId: 'G-4J2RLNLFQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS00C7pPIo0fCbfTMtVn7JatC0Fh8Cs7U',
    appId: '1:413352872203:android:9e9ec75a10627897053a0e',
    messagingSenderId: '413352872203',
    projectId: 'grasp-a122f',
    storageBucket: 'grasp-a122f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3C5xKY3gNqwGGkqo_M_6RjrODAAfAEHE',
    appId: '1:413352872203:ios:dbbd1262f4e8cfb2053a0e',
    messagingSenderId: '413352872203',
    projectId: 'grasp-a122f',
    storageBucket: 'grasp-a122f.appspot.com',
    iosClientId: '413352872203-e0caqlphi6mphpen86i2sakggk735jo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.graspApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3C5xKY3gNqwGGkqo_M_6RjrODAAfAEHE',
    appId: '1:413352872203:ios:dbbd1262f4e8cfb2053a0e',
    messagingSenderId: '413352872203',
    projectId: 'grasp-a122f',
    storageBucket: 'grasp-a122f.appspot.com',
    iosClientId: '413352872203-e0caqlphi6mphpen86i2sakggk735jo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.graspApp',
  );
}
